version: "3"
services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: projectuser
      MYSQL_PASSWORD: supersecretpassword
      MYSQL_ROOT_PASSWORD: supersecretpassword
    volumes:
      - ./data/init:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
  www:
    build: .
    ports:
      - 28001:80
    volumes:
      - ./data/www:/var/www/html/
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    links: 
      - db
    ports:
      - 28000:80
    environment:
      MYSQL_USER: projectuser
      MYSQL_PASSWORD: supersecretpassword
      MYSQL_ROOT_PASSWORD: supersecretpassword
volumes:
  persistent: